### ISSUE TITLE
Lint issue: Invalid package reference in io.grpc:grpc-core

### ISSUE THREAD

**Issue by Filmaluco** [relaycorp/awala-cogrpc-jvm#250] opened 2022-06-06 16:17 UTC
When updating to the 1.1.21 version on a Android app
`implementation 'tech.relaycorp:cogrpc:1.1.21'`

I started getting the following Invalid Package lint issue:
```
../../../../../.gradle/caches/modules-2/files-2.1/io.grpc/grpc-core/1.47.0/3ac5502eaf5fde551b4cde8046cc933587df436/grpc-core-1.47.0.jar: Invalid package reference in io.grpc:grpc-core; not included in Android: javax.naming.directory. Referenced from io.grpc.internal.JndiResourceResolverFactory.JndiRecordFetcher.
../../../../../.gradle/caches/modules-2/files-2.1/io.grpc/grpc-core/1.47.0/3ac5502eaf5fde551b4cde8046cc933587df436/grpc-core-1.47.0.jar: Invalid package reference in io.grpc:grpc-core; not included in Android: javax.naming. Referenced from io.grpc.internal.JndiResourceResolverFactory.JndiRecordFetcher.
```

Is there a way to silence this at the library level to avoid ignoring the lint check?

**Comment by Filmaluco** [comment] 2022-10-27 10:25
So according to this: 
https://github.com/grpc/grpc-java/issues/5422 
and
https://github.com/grpc/grpc-java/commit/b7dd92e7bb3fbc476a186177aee39230440238bd

We should not be having this issue... 

I even inspected the code, and indeed they have the suppression on 
![Screenshot 2022-10-27 at 11 24 14](https://user-images.githubusercontent.com/20781703/198260392-46cefd19-ff60-44e4-8807-6053dd8d57d1.png)

Trying to dig deeper ⛏️

**Comment by gnarea** [comment] 2022-10-27 10:48
Thanks for looking into this @Filmaluco!

My main concern was that this lint issue could point to a real/potential issue in production, but according to the issue you linked to above, the worst that could happen is that a gRPC server could crash.

And since this lib is just a gRPC client, I think we should just silence it in the apps if we can't quickly find a way to silence it at the lib level.

As for the potential gRPC server issue, it could theoretically only affect the courier app (not the gateway), but it's been tested extensively in older phones, so I don't think we need to worry about it either. Since the problem is that certain Java classes would be missing, I reckon it'd be fairly easy to reproduce if it were actually happening.

**Comment by Filmaluco** [comment] 2022-10-27 10:58
@gnarea the lint rules were already suppressing this, I opened the issue so not all apps that use the lib would have to do it... But with your approval, I will leave the lint suppression on the apps (such as the [Android Gateway](https://github.com/relaycorp/relaynet-gateway-android/blob/master/app/lint.xml)) and close this issue.

I will also try to re-open the issue on grpc/grpc-java just to try and have an answer on why this issue came back.

**Comment by gnarea** [comment] 2022-10-27 11:00
Sounds good. Thank you!

**Comment by Filmaluco** [comment] 2022-10-27 11:12
Opened https://github.com/grpc/grpc-java/issues/9661

**Comment by sdsantos** [comment] 2023-11-16 15:24
I tried taking out the `<ignore path="**/grpc-core*.jar" />` on the Gateway app and it worked fine with cogrpc 1.1.31. The answer on https://github.com/grpc/grpc-java/issues/9661 also didn't provide any alternative. Maybe we can close this @gnarea?

**Comment by gnarea** [comment] 2023-11-16 16:17
Sounds good @sdsantos!

**Closed by gnarea** 2023-11-16 16:17 UTC
